apiVersion: apps/v1
kind: Deployment
metadata:
  name: project4-deployment
  labels:
    app: project4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project4
  template:
    metadata:
      labels:
        app: project4
    spec:
      containers:
      - name: project4
        image: 1sharathchandra/project4:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: project4-service
spec:
  type: LoadBalancer
  selector:
    app: project4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
